sdm_genie:
  outputs:
    final:
      type: spark
      method: thrift
      host: "{{ env_var('SPARK_THRIFT_HOST') }}"
      port: 10000
      schema: sdm
      threads: 10
      auth: NOSASL
  target: final