sdm_genie:
  outputs:
    dev:
      host: acea8a1d5bf974f2f8bcb07f52d2a82e-63c19fd1a188d6c3.elb.us-east-2.amazonaws.com
      method: thrift
      port: 10000
      schema: sdm_test
      threads: 1
      type: spark
    final:
      type: spark
      method: thrift
      host: "{{ env_var('SPARK_THRIFT_HOST') }}"
      port: 10000
      schema: sdm
      threads: 10
  target: dev