apiVersion: v1
kind: ingestion
metadata:
  name: sensor-name
  tags:
  - winevent sources
  - authentication
  annotations: {}
source:
  name: ad
  comment:
  dataType: json
  isMultiline: false
  s3:
    bucket: sds
    objectKey: raw/ad
srdm:
  name: ad
  parserClassName: AutoJSON
  jobConf:
    sparkConf:
      - spark.app.name: winevent auto parser
sdm: 
  name: ad
  transformations:
    field1: upper(key1)
    field2: upper(key2)
  outputColumns:
   - field1
   - field2
orchestration:
  cron: '*/1 * * * *'

